### ISSUE TITLE
Does the plugin work on mac?

### ISSUE THREAD

**Issue by ghigo** [mll-freiburg/lr-facetags#2]
I'm able to install the plugin on mac but it looks like nothing happen when I open the plugin at File -> Plugin Extras -> Lr Facetags
Is it supposed to work on mac?

**Comment by ghigo** [comment]
The problem still looks the same with the new version. Is it supposed to work on mac?
When I run the plugin I don't see any progress bar and nothing happen.

**Comment by Krxsy** [comment]
First of all thank you for your interest.
Unfortunately we stopped working on the project due to lack of time. That's why it still doesn't work on mac.
